### ISSUE TITLE
Unexpected big icons

### ISSUE THREAD

**Issue by onlineapps-cloud** [winapps-org/WinApps-Launcher#11] opened 2024-09-06 15:04 UTC
Hi, when i made right click in winapps launcher i get popup with big icons, after selecting apps, i have normal app launcher
![image](https://github.com/user-attachments/assets/295ed4db-0f99-40d0-96cf-aa40dff39347)

https://github.com/user-attachments/assets/6bac2aa2-c949-4565-b197-fbc349ffb0d2

**Comment by oskardotglobal** [comment] 2024-09-06 15:29
This is a duplicate of #8

**Closed by oskardotglobal** 2024-09-06 15:29 UTC
